development:
    OTHER_AUTHCLIENT = 'TVXbdzmpSFvpV7IdbtUIFlgBTGOOfas3'
    OTHER_AUTHSECRET = 'fe1g5pdmExhpm4_B0s9PaaCN68RP-ocHZb8CBIrEn9vun3XZgKAuTj4U_dv3wthU'
    OTHER_PAYPALCLIENT = 'AaY0_-dRiUxZXD3-qDlA3Ua_lBbLqucTflOH0Wf7PknYHQOV8rkydt0Ulsx7emTZEZg1w9hGQ5168hY3'
    OTHER_PAYPALSECRET = 'EAhQg2VIQAvCQDieT9ya-WFkpYnrRrK9Ajd-EuRBgbD-LZSXkZigTetLtfMfl_SdkQreeA8pEP0Tb_j8'